### ISSUE TITLE
Detected an entity reference loop

### ISSUE THREAD

**Issue by wasimali356** [ThomHurks/dblp-to-csv#6]
Please fix this issue 
![error](https://user-images.githubusercontent.com/75903422/101988759-9880de80-3cbd-11eb-8764-a73576dcb751.JPG)

**Comment by ThomHurks** [comment]
Hey! I can't reproduce your problem. I just downloaded the latest DBLP files:
- dblp.dtd with timestamp 2019-11-22 21:20  
- dblp.xml with timestamp 2020-12-11 22:44
And ran the following command (same as yours):
```python3 XMLToCSV.py dblp.xml dblp.dtd outputfile.csv```
and my output is:
```
Start!
Reading elements from DTD file...
Finding unique attributes for all elements...
Opening output files...
Parsing XML and writing to CSV files...
Done after 793.827592 seconds
```
And then I have 8 CSV files as output in my working directory.

The only difference I can think of is maybe the versions of Python3 and LXML you used?
I used:
- lxml version 4.6.2
- Python3 version 3.9.1

Could you maybe verify it works with those versions? And be sure to use the same versions of the DBLP files as I used, so the XML as of 2020-12-11 22:44. The error itself suggests a problem with the DBLP XML file, not with my Python code, so it may actually just be that the DBLP XML file temporarily had an issue which is now fixed.

**Comment by wasimali356** [comment]
Thanks for reply. I have same lxml and python3 version as yours. And also downloaded latest dblp.xml and dblp.dtd but still getting same error.

**Comment by wasimali356** [comment]
Well issue is with dblp.xml file as i have downloaded an older release of dblp.xml file and it worked file but newer version is not working for me.

**Comment by wasimali356** [comment]
Its working now after dblp.xml new update. Thanks
